"""Sprint Report Generator."""
from datetime import datetime, UTC
import json
from pathlib import Path

from src.gold_research.core.paths import ProjectPaths
from src.gold_research.store.db import get_connection

class SprintReport:
    """Consolidates registry activity into an Executive Briefing."""

    @staticmethod
    def _find_run_dir(run_id: str, experiment_id: str) -> Path | None:
        path = ProjectPaths.RESULTS / "raw_runs" / experiment_id / run_id
        return path if path.exists() else None

    @staticmethod
    def _load_scorecard(run_id: str, experiment_id: str) -> dict | None:
        run_dir = SprintReport._find_run_dir(run_id, experiment_id)
        if run_dir is None:
            return None
        scorecard_path = run_dir / "scorecard.json"
        if not scorecard_path.exists():
            return None
        with open(scorecard_path, "r", encoding="utf-8") as handle:
            return json.load(handle)
    
    @staticmethod
    def build_sprint_summary(title: str = "Weekly Quant Review"):
        """Compiles the metrics from all active systems."""

        with get_connection() as conn:
            run_rows = conn.execute(
                """
                SELECT runs.run_id, runs.experiment_id, runs.strategy_class_path, promotions.promotion_state
                FROM runs
                LEFT JOIN promotions ON promotions.run_id = runs.run_id
                WHERE runs.status IN ('completed', 'no_trades', 'completed_limited_data')
                """
            ).fetchall()

        best_run = None
        best_scorecard = None
        live_runs = []
        candidates = []

        for row in run_rows:
            row_dict = dict(row)
            scorecard = SprintReport._load_scorecard(row_dict["run_id"], row_dict["experiment_id"])
            if scorecard is None:
                continue
            sharpe = float(scorecard.get("sharpe", 0.0))
            if best_scorecard is None or sharpe > float(best_scorecard.get("sharpe", 0.0)):
                best_run = row_dict
                best_scorecard = scorecard
            if row_dict.get("promotion_state") == "live":
                live_runs.append(row_dict["run_id"])
            if row_dict.get("promotion_state") == "candidate_for_portfolio":
                candidates.append(row_dict["run_id"])

        best_section = "N/A"
        if best_run and best_scorecard:
            strategy_name = best_run["strategy_class_path"].rsplit(".", 1)[-1]
            best_section = (
                f"**{best_run['run_id']}** (`{strategy_name}`) - "
                f"Sharpe {best_scorecard.get('sharpe', 0.0)} "
                f"(Net: ${best_scorecard.get('total_net_profit', 0.0)})"
            )
        
        md = f"""# ⏱️ {title}
Generated on: {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}

## 🏆 Top Historic Performer (All-Time)
{best_section}

## 🚀 Live Production Models
{len(live_runs)} algorithms currently deployed.
{chr(10).join([f"- `{r}`" for r in live_runs]) if live_runs else "*None currently deployed.*"}

## 🔬 Next-in-Line (Pending Final Review)
{len(candidates)} candidates ready for portfolio inclusion.
{chr(10).join([f"- `{r}`" for r in candidates]) if candidates else "*No backtests promoted to candidate stage this sprint.*"}

---
*Generated by the Gold Research Factory Agent.*
"""
        return md
        
    @staticmethod
    def save_report(markdown_content: str, filename: str = "latest_sprint.md"):
        reports_dir = ProjectPaths.DATA / "manifests" / "reports" / "sprints"
        reports_dir.mkdir(parents=True, exist_ok=True)
        
        filepath = reports_dir / filename
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(markdown_content)
            
        return str(filepath)

if __name__ == "__main__":
    # Test generation
    report = SprintReport.build_sprint_summary("Test Sprint Execution")
    SprintReport.save_report(report)
